# https://docs.docker.com/compose/yml/
# Each service defined in docker-compose.yml must specify exactly one of
# image or build. Other keys are optional, and are analogous to their
# docker run command-line counterparts.
#
# As with docker run, options specified in the Dockerfile (e.g., CMD,
# EXPOSE, VOLUME, ENV) are respected by default - you don't need to
# specify them again in docker-compose.yml.
#

version: '3'

services:
  chris_store_dev:
    image:  ${CREPO}/chris_store_dev_backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./store_backend:/usr/src/store_backend
    ports:
      - "8010:8010"
    depends_on:
      - chris_store_dev_db
    labels:
      name: "ChRIS_store"
      role: "Development server"

  chris_store_dev_db:
    image:  mysql:5
    volumes:
      - chris_store_dev_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootp
      - MYSQL_DATABASE=chris_store_dev
      - MYSQL_USER=chris
      - MYSQL_PASSWORD=Chris1234
    labels:
      name: "ChRIS_store MySQL Database"
      role: "Development database"

volumes:
  chris_store_dev_db_data: